services:
  learn-chatbox-gpt: # The name of the service
    # The name of the container
    container_name: learn-chatbox-gpt
    image: learn-chatbox-gpt
    build: .
    environment:
    - HTTP_PROXY=
    - HTTPS_PROXY=

    ports:
      - "8501:8501"
    restart: always
    env_file:
      - .env
